# Relatório de Análise V

## Tratamento de Dados Faltantes

In [3]:
import pandas as pd

In [4]:
dados = pd.read_csv('dados/aluguel_residencial.csv', sep=';')

In [6]:
dados

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU,Valor m2,Tipo Agregado
0,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0,53.33,Apartamento
1,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,0.0,16.67,Apartamento
2,Apartamento,Cachambi,2,0,0,50,1300.0,301.0,17.0,26.00,Apartamento
3,Apartamento,Grajaú,2,1,0,70,1500.0,642.0,74.0,21.43,Apartamento
4,Apartamento,Lins de Vasconcelos,3,1,1,90,1500.0,455.0,14.0,16.67,Apartamento
5,Apartamento,Copacabana,1,0,1,40,2000.0,561.0,50.0,50.00,Apartamento
6,Apartamento,Freguesia (Jacarepaguá),3,0,0,54,950.0,300.0,28.0,17.59,Apartamento
7,Apartamento,Barra da Tijuca,2,1,1,67,1700.0,589.0,147.0,25.37,Apartamento
8,Apartamento,Tijuca,2,1,0,110,1900.0,700.0,138.0,17.27,Apartamento
9,Apartamento,Olaria,3,1,0,68,1000.0,670.0,0.0,14.71,Apartamento
10,Apartamento,Tijuca,2,1,0,78,2000.0,700.0,0.0,25.64,Apartamento
11,Apartamento,Ipanema,3,1,1,125,7000.0,2100.0,463.0,56.00,Apartamento
12,Apartamento,Tijuca,1,0,0,48,750.0,772.0,25.0,15.62,Apartamento
13,Apartamento,Barra da Tijuca,3,3,1,175,4200.0,1500.0,500.0,24.00,Apartamento
14,Apartamento,Botafogo,2,1,0,76,2500.0,740.0,0.0,32.89,Apartamento
15,Apartamento,Copacabana,3,0,0,180,5500.0,1780.0,420.0,30.56,Apartamento
16,Apartamento,Recreio dos Bandeirantes,3,1,1,105,2300.0,648.0,0.0,21.90,Apartamento
17,Apartamento,Leblon,3,1,0,110,3900.0,1500.0,120.0,35.45,Apartamento
18,Apartamento,Jardim Oceânico,3,3,1,200,3500.0,1780.0,496.0,17.50,Apartamento
19,Apartamento,Barra da Tijuca,3,1,2,70,1800.0,1095.0,140.0,25.71,Apartamento
20,Apartamento,Copacabana,4,1,0,244,5000.0,2500.0,4100.0,20.49,Apartamento
21,Apartamento,Barra da Tijuca,3,2,1,110,4500.0,2000.0,450.0,40.91,Apartamento
22,Apartamento,Recreio dos Bandeirantes,2,2,2,90,3000.0,1340.0,0.0,33.33,Apartamento
23,Apartamento,Recreio dos Bandeirantes,3,2,2,100,2600.0,380.0,0.0,26.00,Apartamento
24,Apartamento,Barra da Tijuca,3,1,1,72,2350.0,600.0,70.0,32.64,Apartamento
25,Apartamento,Humaitá,2,2,1,180,4000.0,2500.0,300.0,22.22,Apartamento
26,Apartamento,Recreio dos Bandeirantes,3,1,2,92,2300.0,840.0,200.0,25.00,Apartamento
27,Apartamento,Centro,1,0,0,27,750.0,371.0,19.0,27.78,Apartamento
28,Apartamento,Ipanema,1,0,0,35,2000.0,650.0,75.0,57.14,Apartamento
29,Apartamento,Ipanema,1,0,0,38,1400.0,530.0,77.0,36.84,Apartamento
...,...,...,...,...,...,...,...,...,...,...,...
19568,Quitinete,Catete,0,0,0,24,1100.0,268.0,0.0,45.83,Apartamento
19569,Quitinete,Catete,1,0,0,20,900.0,408.0,25.0,45.00,Apartamento
19570,Quitinete,Botafogo,1,0,0,18,900.0,457.0,0.0,50.00,Apartamento
19571,Quitinete,Centro,1,0,0,32,700.0,300.0,21.0,21.88,Apartamento
19572,Quitinete,Copacabana,1,0,0,25,1000.0,290.0,0.0,40.00,Apartamento
19573,Quitinete,Centro,1,0,0,40,1100.0,300.0,0.0,27.50,Apartamento
19574,Quitinete,Padre Miguel,1,0,0,55,450.0,0.0,0.0,8.18,Apartamento
19575,Quitinete,Vila Isabel,1,0,0,20,920.0,80.0,0.0,46.00,Apartamento
19576,Quitinete,Botafogo,1,0,0,25,1000.0,582.0,24.0,40.00,Apartamento
19577,Quitinete,Leblon,1,0,0,21,1800.0,700.0,27.0,85.71,Apartamento
19578,Quitinete,Catete,1,0,0,30,1100.0,390.0,24.0,36.67,Apartamento
19579,Quitinete,Botafogo,0,0,0,24,1200.0,450.0,30.0,50.00,Apartamento
19580,Quitinete,Flamengo,1,0,0,24,1290.0,283.0,25.0,53.75,Apartamento
19581,Quitinete,Flamengo,1,0,0,29,950.0,400.0,0.0,32.76,Apartamento
19582,Quitinete,Flamengo,1,0,0,29,900.0,555.0,25.0,31.03,Apartamento
19583,Quitinete,Botafogo,1,0,0,18,900.0,463.0,0.0,50.00,Apartamento
19584,Quitinete,Botafogo,1,0,0,25,1100.0,550.0,250.0,44.00,Apartamento
19585,Quitinete,Gardênia Azul,1,0,0,25,490.0,0.0,0.0,19.60,Apartamento
19586,Quitinete,Irajá,1,0,0,20,500.0,0.0,0.0,25.00,Apartamento
19587,Quitinete,Santa Teresa,1,0,0,30,1000.0,200.0,0.0,33.33,Apartamento
19588,Quitinete,Flamengo,1,0,0,22,1000.0,378.0,0.0,45.45,Apartamento
19589,Quitinete,Glória,1,0,0,32,1250.0,320.0,0.0,39.06,Apartamento
19590,Quitinete,Copacabana,1,0,0,36,1600.0,610.0,54.0,44.44,Apartamento
19591,Quitinete,Leblon,1,0,0,32,2400.0,715.0,121.0,75.00,Apartamento
19592,Quitinete,Copacabana,1,0,0,32,1600.0,692.0,0.0,50.00,Apartamento
19593,Quitinete,Glória,1,0,0,10,400.0,107.0,10.0,40.00,Apartamento
19594,Quitinete,Flamengo,1,0,0,23,900.0,605.0,0.0,39.13,Apartamento
19595,Quitinete,Centro,1,0,0,24,1100.0,323.0,0.0,45.83,Apartamento
19596,Quitinete,Copacabana,1,0,0,22,1500.0,286.0,200.0,68.18,Apartamento
19597,Quitinete,Centro,0,0,0,27,800.0,350.0,25.0,29.63,Apartamento

In [7]:
dados.isnull()

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU,Valor m2,Tipo Agregado
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
19568,False,False,False,False,False,False,False,False,False,False,False
19569,False,False,False,False,False,False,False,False,False,False,False
19570,False,False,False,False,False,False,False,False,False,False,False
19571,False,False,False,False,False,False,False,False,False,False,False
19572,False,False,False,False,False,False,False,False,False,False,False
19573,False,False,False,False,False,False,False,False,False,False,False
19574,False,False,False,False,False,False,False,False,False,False,False
19575,False,False,False,False,False,False,False,False,False,False,False
19576,False,False,False,False,False,False,False,False,False,False,False
19577,False,False,False,False,False,False,False,False,False,False,False
19578,False,False,False,False,False,False,False,False,False,False,False
19579,False,False,False,False,False,False,False,False,False,False,False
19580,False,False,False,False,False,False,False,False,False,False,False
19581,False,False,False,False,False,False,False,False,False,False,False
19582,False,False,False,False,False,False,False,False,False,False,False
19583,False,False,False,False,False,False,False,False,False,False,False
19584,False,False,False,False,False,False,False,False,False,False,False
19585,False,False,False,False,False,False,False,False,False,False,False
19586,False,False,False,False,False,False,False,False,False,False,False
19587,False,False,False,False,False,False,False,False,False,False,False
19588,False,False,False,False,False,False,False,False,False,False,False
19589,False,False,False,False,False,False,False,False,False,False,False
19590,False,False,False,False,False,False,False,False,False,False,False
19591,False,False,False,False,False,False,False,False,False,False,False
19592,False,False,False,False,False,False,False,False,False,False,False
19593,False,False,False,False,False,False,False,False,False,False,False
19594,False,False,False,False,False,False,False,False,False,False,False
19595,False,False,False,False,False,False,False,False,False,False,False
19596,False,False,False,False,False,False,False,False,False,False,False
19597,False,False,False,False,False,False,False,False,False,False,False

In [8]:
dados.notnull()

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU,Valor m2,Tipo Agregado
0,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True
5,True,True,True,True,True,True,True,True,True,True,True
6,True,True,True,True,True,True,True,True,True,True,True
7,True,True,True,True,True,True,True,True,True,True,True
8,True,True,True,True,True,True,True,True,True,True,True
9,True,True,True,True,True,True,True,True,True,True,True
10,True,True,True,True,True,True,True,True,True,True,True
11,True,True,True,True,True,True,True,True,True,True,True
12,True,True,True,True,True,True,True,True,True,True,True
13,True,True,True,True,True,True,True,True,True,True,True
14,True,True,True,True,True,True,True,True,True,True,True
15,True,True,True,True,True,True,True,True,True,True,True
16,True,True,True,True,True,True,True,True,True,True,True
17,True,True,True,True,True,True,True,True,True,True,True
18,True,True,True,True,True,True,True,True,True,True,True
19,True,True,True,True,True,True,True,True,True,True,True
20,True,True,True,True,True,True,True,True,True,True,True
21,True,True,True,True,True,True,True,True,True,True,True
22,True,True,True,True,True,True,True,True,True,True,True
23,True,True,True,True,True,True,True,True,True,True,True
24,True,True,True,True,True,True,True,True,True,True,True
25,True,True,True,True,True,True,True,True,True,True,True
26,True,True,True,True,True,True,True,True,True,True,True
27,True,True,True,True,True,True,True,True,True,True,True
28,True,True,True,True,True,True,True,True,True,True,True
29,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...
19568,True,True,True,True,True,True,True,True,True,True,True
19569,True,True,True,True,True,True,True,True,True,True,True
19570,True,True,True,True,True,True,True,True,True,True,True
19571,True,True,True,True,True,True,True,True,True,True,True
19572,True,True,True,True,True,True,True,True,True,True,True
19573,True,True,True,True,True,True,True,True,True,True,True
19574,True,True,True,True,True,True,True,True,True,True,True
19575,True,True,True,True,True,True,True,True,True,True,True
19576,True,True,True,True,True,True,True,True,True,True,True
19577,True,True,True,True,True,True,True,True,True,True,True
19578,True,True,True,True,True,True,True,True,True,True,True
19579,True,True,True,True,True,True,True,True,True,True,True
19580,True,True,True,True,True,True,True,True,True,True,True
19581,True,True,True,True,True,True,True,True,True,True,True
19582,True,True,True,True,True,True,True,True,True,True,True
19583,True,True,True,True,True,True,True,True,True,True,True
19584,True,True,True,True,True,True,True,True,True,True,True
19585,True,True,True,True,True,True,True,True,True,True,True
19586,True,True,True,True,True,True,True,True,True,True,True
19587,True,True,True,True,True,True,True,True,True,True,True
19588,True,True,True,True,True,True,True,True,True,True,True
19589,True,True,True,True,True,True,True,True,True,True,True
19590,True,True,True,True,True,True,True,True,True,True,True
19591,True,True,True,True,True,True,True,True,True,True,True
19592,True,True,True,True,True,True,True,True,True,True,True
19593,True,True,True,True,True,True,True,True,True,True,True
19594,True,True,True,True,True,True,True,True,True,True,True
19595,True,True,True,True,True,True,True,True,True,True,True
19596,True,True,True,True,True,True,True,True,True,True,True
19597,True,True,True,True,True,True,True,True,True,True,True

In [10]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19598 entries, 0 to 19597
Data columns (total 11 columns):
Tipo             19598 non-null object
Bairro           19598 non-null object
Quartos          19598 non-null int64
Vagas            19598 non-null int64
Suites           19598 non-null int64
Area             19598 non-null int64
Valor            19598 non-null float64
Condominio       19598 non-null float64
IPTU             19598 non-null float64
Valor m2         19598 non-null float64
Tipo Agregado    19598 non-null object
dtypes: float64(4), int64(4), object(3)
memory usage: 1.6+ MB

In [13]:
dados[dados['Valor'].isnull()]

Empty DataFrame
Columns: [Tipo, Bairro, Quartos, Vagas, Suites, Area, Valor, Condominio, IPTU, Valor m2, Tipo Agregado]
Index: []

In [17]:
A = dados.shape[0]
dados.dropna(subset=['Valor'], inplace = True)
B = dados.shape[0]
A - B

0

## Tratamento de Dados Faltantes (continuação)

In [19]:
dados[dados['Condominio'].isnull()].shape[0]

0

In [20]:
selecao = (dados['Tipo'] == 'Apartamento') & (dados['Condominio'].isnull())

In [21]:
A = dados.shape[0]
dados = dados[~selecao]
B = dados.shape[0]
A - B

0

In [23]:
# Preenche as colunas nulas com 0
dados = dados.fillna({'Condominio': 0, 'IPTU': 0})